libs =

define ld: file
ld{*}: extension = ld

mingw32 = ($cxx.target.system == 'mingw32')

exe{mana}: {hxx ixx txx cxx}{**} $libs testscript
exe{mana}: ldscripts/ld{i686-w64-mingw32-g++}: include = ($mingw32 ? adhoc : false)

cxx.poptions =+ "-I$out_root" "-I$src_root"
if $mingw32
  cxx.loptions =+ "-Wl,--large-address-aware,--script=$src_base/ldscripts/i686-w64-mingw32-g++.ld"
