libs =

exe{mana}: {hxx ixx txx cxx}{**} $libs testscript
exe{mana}: ldscripts/file{i686-w64-mingw32-g++.ld}: include = adhoc

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "-Wl,--large-address-aware,--script=$src_base/ldscripts/i686-w64-mingw32-g++.ld"
